project:
  type: website
  output-dir: docs

website:
  title: "Sky Suh "
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - papers.qmd
      - text: "CV"
        file: SkySuhCV.pdf

  page-footer: 
    right: 
      - icon: github
        href: https://github.com/sjp2023
    border: true
    
format:
  html:
    theme: LUX
    css: custom.css
    toc: true



